const cn = {
  info0:'网站设定',
  info1:'该网站名已存在',
  info2:'网站名不能使用空格',
  info3:'一旦设置不能更改',
  info4:'网站名',
  info5:'域名',
  info6:'选填',
  info7:'必填',
  info8:'英文、数字、不允许空格',
  info9:'该名字可用，确认使用该网站名？',
  info10:'备注信息',
  info11:'网站管理',
  info12:'账户设置',
  info13:'保存',
  info14:'保存并上线',
  info15:'预览',
  info16:'编辑',
  info17:'组件库',
  info18:'关键字',
  info19:'元',
  info20:'日',
  info21:'GIF',
  info22:'页面管理',
}

export default cn;